### ISSUE TITLE
Project ideas by Peter

### ISSUE THREAD

**Issue by jibinjohny93** [jibinjohny93/IMDb-Movie-Search#3]

**Comment by Darockofgibraltar** [comment]
Creating an IMDb app using python involves several steps like setting up a webserver, creating a database, fetching data from IMDb or another movie database, and creating a user interface. 

These I think are the following steps:

1. Setting up the environment:

-  Setting up the necessary libraries on Python,
-  Use a virtual environment like venv, Pipenv, PyCharm to manage dependencies (i.e dependencies means a piece of software that relies on other software)

2. Fetch Movie Database:

-  Use the IMDbPY library to fetch data from IMDb
- Alternatively we can also use an API like the Movie Database (TMDb) API to get movie data

3. Set Up a Database:

-  Use SQLite, MySQL, or PostgreSQL to store movie data
-  Design tables for movies genres, ratings, e.t.c

4. Create A Web Server:

- we can do this by using flask or Django to create a web server.
- Define routes for displaying movie list, details ratings and e.t.c

5. Create User Interface:

-  Use HTML, CSS and Java script for front end
- Use Templates in Flask/Django to render pages. 

6. Implement Implement Functionality:

- Allow users to rate movies. 
- Display ratings and analyze them based on genre
